; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 40000000L

; [FLASH MODE]
; If you getting erros compiling in Windows, try setting 'flash_mode' to 'qio'
;
board_build.flash_mode = dout

board_build.partitions = min_spiffs.csv

build_flags =
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
;	-DCORE_DEBUG_LEVEL=5
monitor_speed = 115200

; [UPLOAD ON WINDOWS]
; Uncoment 'upload_port' and 'monitor_port' if with you are compiling in Windows
;
;upload_port = COM3
;monitor_port = COM3

; [UPLOAD SPEED]
; Higher 'upload_speed' values can cause errors on upload if you using USB adaptors
; You can try 921600 if you using direct conection to USB port
;
upload_speed = 115200

lib_deps = 
	bblanchon/ArduinoJson @ ~6.18.0
	https://github.com/scottchiefbaker/ESP-WebOTA.git
